<?php
//Append js-fil
$this->headScript()->prependFile($this->basePath() . '/js/module/timereg/add.js');
$this->headScript()->prependFile($this->basePath() .'../js/jquery.datetimepicker.js');
$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))->prependStylesheet('../js/jquery.datetimepicker.css');

?>

<?php
//Page title
$title = $this->translate('Create new time registration');
$this->headTitle($title);
?>

<!--Heading-->
<div id="contentpageheader">
    <h1>
                <span class="headerlogo fa fa-book"></span>
                <span class="h1text"> <?= $title ?> <span>                
                </h1>
                </div>  

                <div id="taskadd">
                    <!--Render form-->
                    <?php
                    $form->setAttribute('action', $this->url(
                                    'timereg', array(
                                'action' => 'add',
                                //'id' => $project->getProjectid(),
                                    )
                    ));
                    $form->prepare();

                    //Form content
                    echo $this->form()->openTag($form);
                   
                    ?>
                    
                    <div id="error-div" class="alert label-danger hidden" role="alert">
                        <?php foreach ($this->messages as $message) : ?>
                            <?php if (is_string($message)) : ?>
                                <strong class="white-text"><?php echo $message ?></strong>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        <?php foreach ($form as $element) : ?>
                            <?php if (!empty($this->formElementErrors($element))) : ?>
                                <label class="control-label white-text"><?php echo $this->translate($element->getLabel()) ?></label>
                                <strong class="white-text"><?php echo $this->formElementErrors($element) ?></strong>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>

                    <div class="container form-group">
                        <?php foreach ($form as $element) : ?>
                            <?php if ($element->getName() != 'submit' && $element->getName() !== 'projectid') : ?>
                                <?php $element->setAttribute('class', 'form-control'); ?>
                                <div class="control-group form-group">
                                    <label class="control-label"><?php echo $this->translate($element->getLabel()) ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($element); ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                </div>
                <br />
                <div class="container <?php echo $form->get('submit')->getName(); ?>">
                    <?php echo $this->formRow($form->get('submit')); ?>
                </div>




