
<?php
$title = $this->translate('Reset password');
$this->headTitle($title);
?>

<div id="contentpageheader">
    <span class="headerlogo fa fa-user fa-3x"></span>
    <h1 class="text-center h1text"> <?php echo $this->escapeHtml($title); ?> </h1>                
</div>
<p class="btn-danger"> 
    <?php
    if (!empty($this->messages)) {
        foreach ($this->messages as $message) {
            echo 'error: ' . $message . PHP_EOL;
        }
    }
    ?> 
</p>
<?php
if (!isset($this->cancelled)) :
    // form content
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    ?>
    <div class="form-group">
        <?php foreach ($form as $element) : ?>
            <?php if ($element->getName() != 'submit' && $element->getName() != 'id') : ?>
                <?php $element->setAttribute('class', 'form-control'); ?>
                <div class="control-group  form-group">
                    <label class="control-label"><?php echo $element->getLabel() ?></label>
                    <div class="controls">
                        <?php echo $this->formElement($element); ?>
                        <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                    </div>
                </div>
            <?php elseif ($element->getName() == 'id') : ?>
                <div class="controls">
                    <?php
                    echo $this->formElement($form->get('id'));
                    if ($this->formElementErrors($form->get('id'))) : endif;
                    ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($form->get('id')) ?></span>
                </div>
            <?php else : ?>
                <div class = "form-submit-button">
                    <?php $form->get('submit')->setAttribute('class', 'btn btn-success'); ?>
                    <?php echo $this->formRow($form->get('submit')); ?>
                    <?php if ($this->formElementErrors($form->get('submit'))) : ?>
                        <span class="help-inline"> <?php echo $this->formElementErrors($form->get('submit')) ?> </span>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    <?php
 endif;
