<?php

namespace DoctrineORMModule\Proxy\__CG__\Fluxuser\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FluxUser extends \Fluxuser\Entity\FluxUser implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'id', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'employeeId', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'firstname', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'lastname', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'phone', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'privateEmail', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'workEmail', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'username', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'password', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'street', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'houseNumber', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'city', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'zipCode', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'country', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'phonePrivate', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'state', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'pivotaltrackerapi', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'fkuserrole', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'fkaccountid');
        }

        return array('__isInitialized__', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'id', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'employeeId', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'firstname', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'lastname', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'phone', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'privateEmail', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'workEmail', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'username', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'password', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'street', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'houseNumber', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'city', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'zipCode', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'country', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'phonePrivate', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'state', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'pivotaltrackerapi', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'fkuserrole', '' . "\0" . 'Fluxuser\\Entity\\FluxUser' . "\0" . 'fkaccountid');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FluxUser $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeeId($employeeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeeId', array($employeeId));

        return parent::setEmployeeId($employeeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeeId', array());

        return parent::getEmployeeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', array($firstname));

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', array());

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', array($lastname));

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', array());

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrivateEmail($privateEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrivateEmail', array($privateEmail));

        return parent::setPrivateEmail($privateEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrivateEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrivateEmail', array());

        return parent::getPrivateEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkEmail($workEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkEmail', array($workEmail));

        return parent::setWorkEmail($workEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkEmail', array());

        return parent::getWorkEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet($street)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet', array($street));

        return parent::setStreet($street);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet', array());

        return parent::getStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setHouseNumber($houseNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHouseNumber', array($houseNumber));

        return parent::setHouseNumber($houseNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getHouseNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHouseNumber', array());

        return parent::getHouseNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode($zipCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', array($zipCode));

        return parent::setZipCode($zipCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', array());

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhonePrivate($phonePrivate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhonePrivate', array($phonePrivate));

        return parent::setPhonePrivate($phonePrivate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhonePrivate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhonePrivate', array());

        return parent::getPhonePrivate();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setPivotaltrackerapi($pivotaltrackerapi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPivotaltrackerapi', array($pivotaltrackerapi));

        return parent::setPivotaltrackerapi($pivotaltrackerapi);
    }

    /**
     * {@inheritDoc}
     */
    public function getPivotaltrackerapi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPivotaltrackerapi', array());

        return parent::getPivotaltrackerapi();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkuserrole(\Fluxuser\Entity\Usergroup $fkuserrole = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkuserrole', array($fkuserrole));

        return parent::setFkuserrole($fkuserrole);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkuserrole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkuserrole', array());

        return parent::getFkuserrole();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkaccountid(\Fluxuser\Entity\Systemaccount $fkaccountid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkaccountid', array($fkaccountid));

        return parent::setFkaccountid($fkaccountid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkaccountid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkaccountid', array());

        return parent::getFkaccountid();
    }

}
