<?php

namespace DoctrineORMModule\Proxy\__CG__\Fluxuser\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Taskowner extends \Fluxuser\Entity\Taskowner implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Fluxuser\\Entity\\Taskowner' . "\0" . 'taskownerid', '' . "\0" . 'Fluxuser\\Entity\\Taskowner' . "\0" . 'fkuserid', '' . "\0" . 'Fluxuser\\Entity\\Taskowner' . "\0" . 'fktaskid', '' . "\0" . 'Fluxuser\\Entity\\Taskowner' . "\0" . 'fkaccountid');
        }

        return array('__isInitialized__', '' . "\0" . 'Fluxuser\\Entity\\Taskowner' . "\0" . 'taskownerid', '' . "\0" . 'Fluxuser\\Entity\\Taskowner' . "\0" . 'fkuserid', '' . "\0" . 'Fluxuser\\Entity\\Taskowner' . "\0" . 'fktaskid', '' . "\0" . 'Fluxuser\\Entity\\Taskowner' . "\0" . 'fkaccountid');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Taskowner $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTaskownerid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getTaskownerid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaskownerid', array());

        return parent::getTaskownerid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkuserid(\Fluxuser\Entity\FluxUser $fkuserid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkuserid', array($fkuserid));

        return parent::setFkuserid($fkuserid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkuserid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkuserid', array());

        return parent::getFkuserid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFktaskid(\Fluxuser\Entity\Task $fktaskid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFktaskid', array($fktaskid));

        return parent::setFktaskid($fktaskid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFktaskid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFktaskid', array());

        return parent::getFktaskid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkaccountid(\Fluxuser\Entity\Systemaccount $fkaccountid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkaccountid', array($fkaccountid));

        return parent::setFkaccountid($fkaccountid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkaccountid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkaccountid', array());

        return parent::getFkaccountid();
    }

}
