<!--Logout email-->
<h1><?= $this->translate('Task stoppet by logout in FLUXtime'); ?></h1>
<br />
<br />
<p><?= $this->translate('Dear ') . $name; ?>.</p>
<p><?= $this->translate('A task was stopped by logout in FLUXtime. Please contact your FLUXtime'
        . ' admin if you stopped working on the task before logout and the time registration needs to be corrected.'
        . ' You can see you time registrations by clicking the menu "My log" in FLUXtime. Kind regards - FLUXtime '); ?>.</p>




        
 
        

