<?php
$this->headScript()->appendFile('../js/jQueryRotate.js');
$this->headScript()->appendFile('../js/module/error/errorpage.js');
$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))->prependStylesheet('../css/errorpage.css');
?>

<div id="errorpage" style="">
    <br>
    <h1><?php echo $this->translate('An error occurred') ?></h1> 
    <br>
    <i class="fa fa-frown-o fa-5x"></i>
    <p><?php echo $this->translate('An error happend on the page.') ?></p>
    <p><?php echo $this->translate('Check your browser\'s address bar to see whether the URL is correct.'); ?></p>    
</div>



<div id="clickable">
    <i><?php echo $this->translate('More information') ?></i>

    <div id="hideable">
        <h2><?php echo $this->message ?></h2>

        <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

            <?php if (isset($this->exception) && $this->exception instanceof Exception): ?>
                <hr/>
                <h2><?php echo $this->translate('Additional information') ?>:</h2>
                <h3><?php echo get_class($this->exception); ?></h3>
                <dl>
                    <dt><?php echo $this->translate('File') ?>:</dt>
                    <dd>
                        <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
                    </dd>
                    <dt><?php echo $this->translate('Message') ?>:</dt>
                    <dd>
                        <pre class="prettyprint linenums"><?php echo $this->escapeHtml($this->exception->getMessage()) ?></pre>
                    </dd>
                    <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                    <dd>
                        <pre class="prettyprint linenums"><?php echo $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
                    </dd>
                </dl>
                <?php
                $e = $this->exception->getPrevious();
                if ($e) :
                    ?>
                    <hr/>
                    <h2><?php echo $this->translate('Previous exceptions') ?>:</h2>
                    <ul class="unstyled">
                        <?php while ($e) : ?>
                            <li>
                                <h3><?php echo get_class($e); ?></h3>
                                <dl>
                                    <dt><?php echo $this->translate('File') ?>:</dt>
                                    <dd>
                                        <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                                    </dd>
                                    <dt><?php echo $this->translate('Message') ?>:</dt>
                                    <dd>
                                        <pre class="prettyprint linenums"><?php echo $this->escapeHtml($e->getMessage()) ?></pre>
                                    </dd>
                                    <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                                    <dd>
                                        <pre class="prettyprint linenums"><?php echo $this->escapeHtml($e->getTraceAsString()) ?></pre>
                                    </dd>
                                </dl>
                            </li>
                            <?php
                            $e = $e->getPrevious();
                        endwhile;
                        ?>
                    </ul>
                <?php endif; ?>

            <?php else: ?>

                <h3><?php echo $this->translate('No Exception available') ?></h3>

            <?php endif ?>

        <?php endif ?>
    </div>
</div>





